version: '3.3'
services:
  litecoin-testnet:
    #image: uphold/litecoin-core:0.16.0
    build:
      context: ./
      dockerfile: Dockerfile
    command: --printtoconsole -txindex=1 -server=1 -listen=1 -testnet=1 -rpcallowip=0.0.0.0/0 -rpcuser=admin1 -rpcpassword=123
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    networks:
      - crypto-p2p-services
    volumes:
      - litecoin-testnet:/home/litecoin/.litecoin
    ports:
      - 19332:19332
      - 19333:19333 #p2p

networks:
  crypto-p2p-services:
    external: true

volumes:
  litecoin-testnet:
