version: '3.3'
services:
  litecoin-testnet:
    build:
      context: ./
      dockerfile: Dockerfile
    command: --printtoconsole -txindex=1 -server=1 -listen=1 -testnet=1 -port=20001 -rpcallowip=0.0.0.0/0 -rpcuser=admin1 -rpcpassword=123 -rpcport=20011
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    networks:
      - web-services
    ports:
      - 20001:20001
      - 20011:20011

networks:
  web-services:
    external: true
